### ISSUE TITLE
fatal error when only one target question

### ISSUE THREAD

**Issue by GeoBen93** [demichie/elicipy#5]
Hello, 

I have succesfully been running elicipy on a number of elicitations. However, on the latest elicitation with one question I recieve the following fatal error message:

The new directory C:\Users\######\elicipy-main/ELICITATIONS/Ixchel_test/OUTPUT is created!
STEP1: Reading questionnaire
STEP2: Reading all answers to define ranges
       Merging of individual csv files
       Merging target
The new directory ../TARGET_NEW is created!
       Saving target answers
       |██████████████████████████████████████████████████| 100.0%
STEP3: Reading answers for group  0
       Merging of individual csv files
       Merging target
  First Name    Last Name  C  I_tot  I_real  w  normW
0       name       redacted  0      0       0  0   12.5
1       name       redacted  0      0       0  0   12.5
2    name       redacted  0      0       0  0   12.5
3     name       redacted  0      0       0  0   12.5
4     name       redacted  0      0       0  0   12.5
5    name       redacted  0      0       0  0   12.5
6      name       redacted  0      0       0  0   12.5
7    name       redacted  0      0       0  0   12.5
       Creating samples for questions
C:\Users\######\elicipy-main\tools.py:24: RuntimeWarning: invalid value encountered in divide
  percents = str_format.format(100 * (iteration / float(total)))
C:\Users\######\elicipy-main\tools.py:25: RuntimeWarning: invalid value encountered in divide
  filled_length = int(round(bar_length * iteration / float(total)))
Traceback (most recent call last):
  File "C:\Users\######\elicipy-main\elicipy.py", line 2917, in <module>
    main(sys.argv[1:])
  File "C:\Users\######\elicipy-main\elicipy.py", line 1545, in main
    create_samples(group, n_experts, n_SQ, n_TQ, n_pctl, SQ_array,
  File "C:\Users\######\elicipy-main\elicipy.py", line 934, in create_samples
    printProgressBar(j, n_SQ + n_TQ - 1, prefix='      ')
  File "C:\######\elicipy-main\tools.py", line 25, in printProgressBar
    filled_length = int(round(bar_length * iteration / float(total)))
ValueError: cannot convert float NaN to integer

I have added a placeholder 2nd question to the questionnaire and questionnaire responses, and this resolves the issue. Looks like it's just a problem with the calculation of the loading bar on the python console when there is only one question.

**Comment by demichie** [comment]
Hi,
I've make a small change but I cannot test it because I'm with laptop only and traveling.
I hope it works.

**Comment by GeoBen93** [comment]
Hi,
Sorry it's taken so long replying to this, really appreciate your assistance.

I have downloaded the updated code but I am unfortunately I am still getting the same error as above when eliciting only 1 target question.

Thanks

**Comment by demichie** [comment]
Hi! I am traveling now. Please can you send me a reminder by email to check this thing in a couple of weeks?

Thanks!

**Comment by GeoBen93** [comment]
Absolutely, no problem. I'll send a reminder in a few weeks. Thanks!

**Comment by demichie** [comment]
Hi,
Do you have both seed and target questions, or only one target with weights read from a file?

Mattia

**Comment by demichie** [comment]
Hi Ben,
Can you test if now it works?

Mattia

**Comment by GeoBen93** [comment]
Hi Mattia, 
I have just tested it and it is now working as expected with 1 target question only. Apologies I didn't get back to you before.
Thanks for  your help,
Ben
